spring:
  #  redis配置
  redis:
    # redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # Redis数据库索引(默认0)
    database: 1
    # 连接超时时间（毫秒）
    timeout: 10000
    #Lettuce 是一个可伸缩线程安全的 Redis 客户端，多个线程可以共享同一个 RedisConnection，它利用优秀 netty NIO 框架来高效地管理多个连接
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      # 关闭超时时间
      shutdown-timeout: 100

  #    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  # 应用服务名称
  application:
    name: SpringBoot
  # 指定需要加载的配置文件
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:xml/*Mapper.xml
  typeAliasesPackage: com.demo.entity
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    cache-enabled: false
  # 全局策略配置
  global-config:
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: true
    db-config:
      # id类型
      id-type: auto
      # 表名是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true

# xxl-job 任务调度中心
xxl:
  job:
    admin:
      # xxlJobAdmin 管理控制调度平台（配合使用，方便管理任务bean，需要自己部署，已有开源项目）
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      ip: 127.0.0.1
      port: 5588
      logpath: /home/xxlJoblogs
      logretentiondays: 30
      appname: name
    accessToken:

jwt:
  # 自行配置密钥
  secret: test

server:
  port: 8888
